version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # For the web frontend
      - "4000:4000"  # For the backend API
    environment:
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL:-http://localhost:3000}
      - NEXT_PUBLIC_API_V2_URL=${NEXT_PUBLIC_API_V2_URL:-http://localhost:4000/api/v2}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}
      - POSTGRES_USER=${POSTGRES_USER:-doadmin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your_password}
      - POSTGRES_DB=${POSTGRES_DB:-rls_calcom_calendar}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
    networks:
      - cal_network

networks:
  cal_network:
    driver: bridge

